name: sm_academy
description: "A new Flutter project for SM Academy."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # المكتبات الأساسية والواجهات
  provider: ^6.1.1
  device_info_plus: ^10.1.0
  screen_protector: ^1.5.1
  google_fonts: ^6.2.1
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5

  # المحرك الجديد الجبار (Media Kit) لتشغيل التابلت والهاتف
  media_kit: ^1.1.10+1
  media_kit_video: ^1.2.4
  media_kit_libs_video: ^1.3.1

  # مكتبات فايربيز (إصدارات مستقرة)
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
