name: sm_academy
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  # المكتبات الأساسية
  provider: ^6.1.1
  device_info_plus: ^10.1.0
  screen_protector: ^1.5.1
  google_fonts: ^6.2.1
  cached_network_image: ^3.3.1
  url_launcher: ^6.2.1
  shared_preferences: ^2.2.2

  # مكتبات الفيديو
  video_player: ^2.8.6
  chewie: ^1.8.1
  youtube_player_flutter: ^9.0.1

  # مكتبات فايربيز
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
